#!/usr/bin/perl -w
use strict;
use Digest::SHA qw/sha1_hex/;
my $seed = time;



my $i;
my @keys;
if (!-e './otp_challenge') {
	print "Generating 100 one-time passwords\n";
	print "Hang onto these and give them out to people that want an account!\n";
	print "And make sure they are used in order, one per person\n";
	for ($i=1; $i <= 99; $i++) {
		$seed = sha1_hex $seed;
#		print "$i $seed\n";
		unshift @keys, $seed;
	}
	$i = 0;
	foreach (@keys) {
		print ++$i." ".$_."\n";
	}
	open (my $fh, '>', './otp_challenge');
	print $fh sha1_hex $seed;
	close $fh;
}
else {
	print "You already have a one-time password file!\n";
	print "If you lost your codes, please delete this file and run ./otp again\n";
}