#!/usr/bin/perl -w
use strict;
use Data::Dumper;
use DBI;
use Archive::Zip;
#
use constant {
	DAILY_DUMP_FILENAME => 'bigmike-nightly.zip',
};

# Turn off STDOUT buffering
$| = 1;
# Associate file key with path
my %files;
# Associate file key with series
my %series;

my ($sqlhost, $sqluser, $sqlpass, $sqldb);
my $tmppath;
open(FILE, '/var/http/hub/hooYa/includes/config.php');
while (<FILE>) {
	$sqlhost = $1 if (/"CONFIG_MYSQL_HOOYA_HOST", ["'](.+)["']/);
	$sqluser = $1 if (/"CONFIG_MYSQL_HOOYA_USER", ["'](.+)["']/);
	$sqlpass = $1 if (/"CONFIG_MYSQL_HOOYA_PASSWORD", ["'](.+)["']/);
	$sqldb = $1 if (/"CONFIG_MYSQL_HOOYA_DATABASE", ["'](.+)["']/);
	$tmppath = $1 if (/"CONFIG_TEMPORARY_PATH", ["'](.+)["']/);
}
my $dsn = "DBI:mysql:database=" . $sqldb . ";host=" . $sqlhost;
my $dbh = DBI->connect($dsn, $sqluser, $sqlpass);

my $sth = $dbh->prepare("SELECT Files.Id, Path FROM Files WHERE"
. " Files.class = 'single_image'");
$sth->execute();
while (my $ref = $sth->fetchrow_hashref()) {
	$files{$ref->{'Id'}} = $ref->{'Path'};
}
my $total = keys %files;
my $current = 0;
my $percent = 0;
my $change = 100 / $total;
unlink($tmppath . 'tmp.zip');

foreach my $key (keys %files) {
	$percent += $change;
	$current++;
	printf("\33[2K\r");
	printf("%.f%% done (%d / %d)", $percent, $current, $total);
	system("zip -j -q -0 -g '".$tmppath."tmp.zip' '$files{$key}'");
	die if $?;
#	system("printf \"zip -z store -u '/var/a/nightly.zip' '$files{$key}'\"");die;
}
printf "\nMoving to serving path. . .\n";
system("mv ".$tmppath."tmp.zip ".$tmppath.DAILY_DUMP_FILENAME);
#system("zip -9 '/var/a/nightly.zip' '/var/a/nightly.zip'");