#!/usr/bin/perl -w
use strict;
use Data::Dumper;
use DBI;
use Archive::Zip;
#
use constant {
	DAILY_DUMP_FILENAME => 'bigmike-nightly.zip',
};

# Turn off STDOUT buffering
$| = 1;
# Associate file key with path
my %files;
# Associate file key with series
my %series;

my ($CONFIG_MYSQL_HOOYA_HOST,
$CONFIG_MYSQL_HOOYA_USER,
$CONFIG_MYSQL_HOOYA_PASSWORD,
$CONFIG_MYSQL_HOOYA_DATABASE,
$CONFIG_TEMPORARY_PATH,
$CONFIG_DAILY_DUMP_PATH);

open(FILE, '/var/http/hub/hooYa/includes/config.php');
while (<FILE>) {
	$CONFIG_MYSQL_HOOYA_HOST = $1 if (/["']CONFIG_MYSQL_HOOYA_HOST["'], ["'](.+)["']/);
	$CONFIG_MYSQL_HOOYA_USER = $1 if (/"CONFIG_MYSQL_HOOYA_USER", ["'](.+)["']/);
	$CONFIG_MYSQL_HOOYA_PASSWORD = $1 if (/["']CONFIG_MYSQL_HOOYA_PASSWORD["'], ["'](.+)["']/);
	$CONFIG_MYSQL_HOOYA_DATABASE = $1 if (/["']CONFIG_MYSQL_HOOYA_DATABASE["'], ["'](.+)["']/);
	$CONFIG_TEMPORARY_PATH = $1 if (/["']CONFIG_TEMPORARY_PATH["'], ["'](.+)["']/);
	$CONFIG_DAILY_DUMP_FILE = $1 if (/["']CONFIG_DAILY_DUMP_FILE["'], ["'](.+)["']/);
}
my $dsn = "DBI:mysql:database=" . $CONFIG_MYSQL_HOOYA_DATABASE
. ";host=" . $CONFIG_MYSQL_HOOYA_HOST;
my $dbh = DBI->connect($dsn,
$CONFIG_MYSQL_HOOYA_USER,
$CONFIG_MYSQL_HOOYA_PASSWORD);

my $sth = $dbh->prepare("SELECT Files.Id, Path FROM Files WHERE"
. " Files.class = 'single_image'");
$sth->execute();
while (my $ref = $sth->fetchrow_hashref()) {
	$files{$ref->{'Id'}} = $ref->{'Path'};
}
my $total = keys %files;
my $current = 0;
my $percent = 0;
my $change = 100 / $total;
unlink($CONFIG_TEMPORARY_PATH . 'nightly-tmp.zip');

foreach my $key (keys %files) {
	$percent += $change;
	$current++;
	printf("\33[2K\r");
	printf("%.f%% done (%d / %d)", $percent, $current, $total);
	system("zip -j -q -0 -g '" . $CONFIG_TEMPORARY_PATH
	. "nightly-tmp.zip' '$files{$key}'");
	die if $?;
#	system("printf \"zip -z store -u '/var/a/nightly.zip' '$files{$key}'\"");die;
}
printf "\nMoving to serving path. . .\n";
system("mv " . $CONFIG_TEMPORARY_PATH . "nightly-tmp.zip "
. $CONFIG_DAILY_DUMP_FILE);