<?php
define("CONFIG_REQUIRE_AUTHENTICATION", false);
define("CONFIG_DB_SERVER", "127.0.0.1");
define("CONFIG_DB_USERNAME", "DB_USERNAME");
define("CONFIG_DB_PASSWORD", "DB_PASSWORD");
define("CONFIG_DB_DATABASE", "DB_DATABASE");
define("CONFIG_DB_TABLE", "DB_TABLE");
?>