=head1 hooYa!

hooYa! is a community-driven file tagger with support for lots of media
types. Users contribute tag associations, which describe each file. Users
can also contribute a number of files each day

You can check out the Scrin mothership of hooYa! at
L<https://bm.howler.space/hub/hooYa>

=head2 Dependencies

=over 12

=item A Webserver

Make sure that your webserver can serve .php files first!

=item PHP

At least >PHP5

=item MySQL (MariaDB)

Storing tags and metadata about indexed files

=item Appropriate MySQL Module for PHP5

For apache, this is C<php5-mysql>

=item B<bm-common>

Common stylesheets and authentication

=item Imagemagick

Generating image thumbnails

=item ffmpegthumbnailer

Generating video thumbnails

=item DBI

Perl module for installation and administration of the database

=item DBD::mysql

Specific Perl module for interacting with SQL

=item Digest::MD5::File

Perl module for calculating MD5 hashes of a file

=back

=head2 Installation

Follow the set up instructions for bm-common; this project provides the
common stylsheets and authentication for the website

Once you've installed bm-common correctly, install hooYa! by
running C<git clone https://howler.space/git/bigmike-hooYa.git>

Then, C<cp includes/config.template.php includes/config.php> and edit the
configuration file to your taste

Lastly, run C<bin/install> to create the hooYa! SQL structure

=head2 Features

=over 12

=item file tagging

Associative namespaces like series -> yuyushiki
Tags are handled by MySQL

=item per-deployment configuration

per-deployment settings are defined in includes/config.php

=item thumbnailing

Dynamic generation of thumbnails; cached

=item tag aliases

Instead of typing puella magi madoka magica every time, I can
just type pmmm. How easy!

=item extensible media classes

Some example classes are included, but it is trivial to index
other media (PDFs, presentations etc.)

=back

=head2 License

Modified BSD License (see C<docs/LICENSE>)

=head2 Contact

Bother me on IRC in #bigtown on C<howler.space:6667> or by mail at
<yumi@howler.space>
